accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
]

profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),
        name='show'),
]

tango/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
from . import views


urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^Tango-In-Hyderabad/$', views.TangoHyderabadPage.as_view(),
        name='Tango-In-Hyderabad'),
    url(r'^Tango-In-Auroville-Pondicherry/$',
        views.TangoAurovillePage.as_view(), name='Tango-In-Auroville-Pondicherry'),
    url(r'^Tango-In-Chennai/$', views.TangoChennaiPage.as_view(),
        name='Tango-In-Chennai'),
    url(r'^Tango-In-Delhi/$', views.TangoNewDelhiPage.as_view(), name='Tango-In-Delhi'),
    url(r'^Tango-In-Bangalore/$', views.TangoBangalorePage.as_view(),
        name='Tango-In-Bangalore'),
    url(r'^Tango-Essentials/$', views.TangoEssentials.as_view(),
        name='Tango-Essentials'),
    url(r'^Tango-Radio/$', views.TangoRadio.as_view(), name='Tango-Radio'),
    url(r'^sitemap_location/$', views.TangoSitemap.as_view(), name='sitemap_location'),
    url(r'^Tango-In-Mumbai/$', views.TangoMumbai.as_view(), name='Tango-In-Mumbai'),
    url(r'^Tango-Events/$', views.EventsPage.as_view(), name='Tango-Events'),
    url(r'^Tango-In-Pune/$', views.TangoPunePage.as_view(), name='Tango-In-Pune'),
    url(r'^Tango-In-Bangalore-El-Cabeceo/$',
        views.TangoElCabeceoPage.as_view(), name='Tango-In-Bangalore-El-Cabeceo'),
    url(r'^Tango-In-Mumbai-BTangoConscious/$',
        views.TangoMumbaiBTangoConscious.as_view(), name='Tango-In-Mumbai-BTangoConscious'),
    url(r'^Past-Events/$', views.PastEventsPage.as_view(), name='Past-Events'),
    url(r'^legal/$', views.LegalTC.as_view(), name='legal'),
    url(r'^Tango-In-Goa/$', views.TangoGoaPage.as_view(), name='Tango-In-Goa'),


]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/Tango-Events1.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Tango Events-milonga-workshop-classes in India{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="Event" %}
{% endblock %}

{% block container %}

<div id="sec1" class="jumbotron" >
   <div class="container">
     <div class="row">      
      <div class="col-md-12 text-center">
        <h1 class="lead"> Tango Events/Milongas/Practicas </h1>
      </div>
    </div>
  </div>
</div>


<div id="sec2" class="jumbotron">
  <div class="container">
    <div class="row">      
      <div class="col-md-12 text-center" >
         <h3><strong><mark>Events coming up in next 15 days! </mark></strong></h3><br>
          <div class="fb-like" data-href="http://thetangoindia.in/Tango-Events" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
             <hr>
            {% if Next2weeks %}
                <ul> 
                    {% for event in Next2weeks %}
                    <div class="well"
                        <h3><strong>Name : </strong>{{ event.Event_Name }}</h3>
                        <p>Description : {{ event.Description }}</p><br/>
                        <img class="img-responsive center-block" src="{{event.Cover}}"/>,
                        <p>Location ID : {{ event.Location }}</p> <p>Event ID : {{ event.Event_Id }}</p>
                        <p>Start_Time : {{ event.Start_Time }}</p>
                        <p>End_Time : {{ event.End_Time }}</p> <p>Place : {{ event.Place }}</p>
                        <p> Last Updated : {{ event.Updated_Time }}</p><p><a href="{{event.Event_Link }}" target="_blank"><strong>Facebook Link</strong></a></p><br/>
                        <p>Attending_Count : {{ event.Attending_Count }}</p>
                        <br/>
                        <hr>
                     </div>
                    {% empty %}
                         <li> No Events coming up in next 15 days.</li>  
                    {% endfor %}
                 </ul>
            {% else %}
                <strong>No Events coming up in next 15 days.</strong>
            {% endif %}
      </div>
    </div>
  <hr>
  <hr>
  <hr>
  <hr>
    <div class="container">
    <div class="row">      
      <div class="col-md-12 text-center" >
         <h3><strong><mark>Future Events coming up after 15 Days! </mark></strong></h3><br>
            {% if FutureEvents %}
                <ul> 
                    {% for event in FutureEvents %}
                    <div class="well"
                        <h3><strong>Name : </strong>{{ event.Event_Name }}</h3>
                        <p>Description : {{ event.Description }}</p><br/>
                        <img class="img-responsive center-block" src="{{event.Cover}}"/>,
                        <p>Location ID : {{ event.Location }}</p> <p>Event ID : {{ event.Event_Id }}</p>
                        <p>Start_Time : {{ event.Start_Time }}</p>
                        <p>End_Time : {{ event.End_Time }}</p> <p>Place : {{ event.Place }}</p>
                        <p> Last Updated : {{ event.Updated_Time }}</p><p><a href="{{event.Event_Link }}" target="_blank"><strong>Facebook Link</strong></a></p><br/>
                        <p>Attending_Count : {{ event.Attending_Count }}</p>
                        <br/>
                        <hr>
                     </div>
                    {% empty %}
                         <li> No Events </li>  
                    {% endfor %}
                 </ul>
            {% else %}
                <strong>No Events found could be server side issue!</strong>
            {% endif %}
      </div>
    </div>
  <hr>
  <hr>
  <hr>
  <hr>
    <div class="container">
    <div class="row">      
      <div class="col-md-12 text-center" >
         <h3><strong><mark>Past Events !</mark></strong></h3><br>
            {% if PastEvents %}
                <ul> 
                    {% for event in PastEvents %}
                    <div class="well"
                        <h3><strong>Name : </strong>{{ event.Event_Name }}</h3>
                        <p>Description : {{ event.Description }}</p><br/>
                        <img class="img-responsive center-block" src="{{event.Cover}}"/>,
                        <p>Location ID : {{ event.Location }}</p> <p>Event ID : {{ event.Event_Id }}</p>
                        <p>Start_Time : {{ event.Start_Time }}</p>
                        <p>End_Time : {{ event.End_Time }}</p> <p>Place : {{ event.Place }}</p>
                        <p> Last Updated : {{ event.Updated_Time }}</p><p><a href="{{event.Event_Link }}" target="_blank"><strong>Facebook Link</strong></a></p><br/>
                        <p>Attending_Count : {{ event.Attending_Count }}</p>
                        <br/>
                        <hr>
                     </div>
                    {% empty %}
                         <li> No Events </li>  
                    {% endfor %}
                 </ul>
            {% else %}
                <strong>No Events found could be server side issue!</strong>
            {% endif %}
      </div>
    </div>
   </div>
   </div>
  </div>
</div>

{% endblock container %}

templates/Tango-In-Bangalore-El-Cabeceo.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Tango In Bangalore{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="Event" %}
{% endblock %}



{% block container %}


<div id="sec1" class="jumbotron" >
   <div class="container">
     <div class="row">
      <div class="col-md-12 text-center">
        <h1 class="lead"> Tango In Bangalore </h1>
      </div>
    </div>
  </div>
</div>


<div class="container">
    <div class="table-responsive">
      <table class="table table-striped ">
        {% if object_list %}
            <tbody>
                <tr>
                  <th scope="row"</th>
                  <td> <strong>Place</strong></td>
                  <td>{{ object_list.category }}</td>
                <tr>
                <tr>
                  <th scope="row"</th>
                  <td><strong>Description</strong></td>
                  <td>{{ object_list.description }}</td>
                </tr>


                <tr>
                  <th scope="row"</th>
                  <td><strong>Email</strong></td>
                  <td>{{ object_list.email }}</td>
                <tr>
                <tr>
                  <th scope="row"</th>
                  <td><strong>Contact Numbers</strong></td>
                  <td>{{ object_list.contact_number }}</td>
                </tr>


                <tr>
                  <th scope="row"</th>
                  <td><strong>Website</strong></td>
                  <td>{{ object_list.website }}</td>
                <tr>
                <tr>
                  <th scope="row"</th>
                  <td><strong>Facebook Page</strong></td>
                  <td><a href="{{ object_list.fb_url }}" target="_blank"><strong>FaceBook Page Link</strong></a></td>
                </tr>


                <tr>
                  <th scope="row"</th>
                  <td><strong>Class Location</strong></td>
                  <td>{{ object_list.class_location }}</td>
                <tr>
                <tr>
                  <th scope="row"</th>
                  <td><strong>CLass Location MAP</strong></td>
                  <td><a href="{{ object_list.class_location_map }}" target="_blank"><strong>Click Here MAP Link</strong></a></td>
                </tr>
                <tr>
                  <th scope="row"</th>
                  <td><strong>CLass Timings</strong></td>
                  <td>{{ object_list.class_timings }}</td>
                </tr>

                <tr>
                  <th scope="row"</th>
                  <td><strong>Practica Venue</strong></td>
                  <td>{{ object_list.practica_venue }}</td>
                <tr>
                <tr>
                  <th scope="row"</th>
                  <td><strong>Practica Time</strong></td>
                  <td>{{ object_list.practica_time }}</td>
                </tr>
                <tr>
                  <th scope="row"</th>
                  <td><strong>Practica Venue MAP Link</strong></td>
                  <td><a href="{{ object_list.practica_venue_map_link }}" target="_blank"><strong>Click Here for MAP</strong></a></td>
                </tr>

                <tr>
                  <th scope="row"</th>
                  <td><strong>Instructor</strong></td>
                  <td>{{ object_list.instructor_name }}</td>
                <tr>
                <tr>
                  <th scope="row"</th>
                  <td><strong>Milonga Venue</strong></td>
                  <td>{{ object_list.milonga_venue }}</td>
                </tr>
                <tr>
                  <th scope="row"</th>
                  <td><strong>Milonga Timings</strong></td>
                  <td>{{ object_list.milonga_time }}</td>
                </tr>
                <tr>
                  <th scope="row"</th>
                  <td><strong>Milonga Venue MAP Link</strong></td>
                  <td><a href="{{ object_list.milonga_venue_map_link }}" target="_blank"><strong>Click Here for MAP</strong></a></td>
                </tr>
                <tr>
                  <th scope="row"</th>
                  <td><strong>Admission Process for Class</strong></td>
                  <td>{{ object_list.admission_process }}</td>
                <tr>

            </tbody>

        {% else %}
           <strong>We are having some technical trouble.... please visit again after some time.</strong>
        {% endif %}
     </table>
   </div>
</div>

<div class="container">
     <div class="row">
      <p> Suggest edit/correction or feedback to thetangoindia@gmail.com.If you are admin of Above Tango COmmunity, register and request for admin rights to edit this page! </p> <a href="http://thetangoin
dia.in/signup/" target="_blank"><strong>Click Here To Register</strong></a>
  </div>
</div>

{% endblock container %}

templates/_brandname.html
Tango In India

templates/_navbar.html
<li {% if active_link == "home" %}class="active"{% endif %}><a href="{% url 'home' %}">Home</a></li>
<li {% if active_link == "about" %}class="active"{% endif %}><a href="{% url 'about' %}">About</a></li>
<li {% if active_link == "Events" %}class="active"{% endif %}><a href="{% url 'Tango-Events' %}">Events</a></li>
<li {% if active_link == "Tango Essentials" %}class="active"{% endif %}><a href="{% url 'Tango-Essentials' %}">Tango Essentials</a></li>
<li {% if active_link == "Tango Radio" %}class="active"{% endif %}><a href="{% url 'Tango-Radio' %}">Tango Radio</a></li>

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    {% load thumbnail %}
    
  <head>
    <meta name="google-site-verification" content="HCxEzRtw_9J4r4cCgpliQJoo1CBirVuYidengDIR5no" />
    <meta name="msvalidate.01" content="14FB3C958FB172CFA1E8C99BEFA1643C" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}Argentine Tango in India: partner-dance,tango-classes,milonga,tango-workshops,tango-events,learn-tango,tango-festivals{% endblock description %}">
    <meta name="author" content="Sandeep Rawat">
    <!--<meta property="og:image" content="https://c7.staticflickr.com/9/8156/29500896982_e3b30951f7_k.jpg"/>-->
    <meta property="og:image" content="https://farm3.staticflickr.com/2915/32807803033_2ce9d5a053_k.jpg"/>
    <link rel="shortcut icon" href="{% static 'site/img/favicon.ico' %}">
    <title>{% block title %}{% include "_brandname.html" %}:Argentine Tango Classes Practicas Milongas in India:{% endblock %}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this site -->
    {% block styles %}
    <link href="{% static 'site/css/main.css' %}" rel="stylesheet">
    {% endblock styles %}

    <!-- Custom tags for the head tag -->
    {% block extrahead %}{% endblock extrahead %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.7&appId=1053293938053804";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
 {% block navbar %}  
   <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">
            {% block navbar-brand %}
              <img src="{% static 'site/img/favicon.ico' %}" alt="logo">
              {% include "_brandname.html" %}
            {% endblock %}
          </a>
        </div>
        {% block navbar-menu %}
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% block navbar-left %}{% endblock %}
			<li class ="dropdown">
				<a class="dropdown-toggle" data-toggle="dropdown" href="#">Tango Locations<span class="caret"></span></a>
				<ul class="dropdown-menu">
					<li><a href="{% url 'Tango-In-Hyderabad' %}">Hyderabad Tango Club</a></li>
                    <li><a href="{% url 'Tango-In-Bangalore' %}">Bangalore Argentine Tango</a></li>
					<li><a href="{% url 'Tango-In-Delhi' %}">NewDelhi Tango School</a></li>
					<li><a href="{% url 'Tango-In-Mumbai' %}">Abrazo Tango Mumbai</a></li>
					<li><a href="{% url 'Tango-In-Auroville-Pondicherry' %}">Tango Auroville-Pondicherry</a></li>
					<li><a href="{% url 'Tango-In-Chennai' %}">Tango Chennai</a></li>
					<li><a href="{% url 'Tango-In-Pune' %}">Pune Tango Community</a></li>
					<li><a href="{% url 'Tango-In-Bangalore-El-Cabeceo' %}">El Cabeceo Bangalore</a></li>
					<li><a href="{% url 'Tango-In-Mumbai-BTangoConscious' %}">BTangoConscious Mumbai</a></li>
					<li><a href="{% url 'Tango-In-Goa' %}">Goa Tango Community</a></li>
				</ul>
			 </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% block navbar-right %}
              {% if user.is_authenticated %}
                {% if user.is_staff %}
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
                {% endif %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle profile-menu" data-toggle="dropdown">
			<img src="{% thumbnail user.profile.picture|default:'default_profile.png' 30x30 crop %}" alt="" />
			{{ user.get_full_name|truncatechars:20 }}
			<span class="caret"></span>
		    </a>
		    
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'profiles:show_self' %}">Profile</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                  </ul>
                </li>
              {% endif %}
            {% endblock %}
          </ul>
          </ul>
        </div><!--/.nav-collapse -->
        {% endblock %}
    </div>
    {% endblock navbar %}

    {% block messages %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">  <!-- singular -->
            <a class="close" data-dismiss="alert">×</a>
            {{ message|safe }}
          </div>
        {% endfor %}
      {% endif %}
    {% endblock %}

    {% block splash %}
    {% endblock splash %}
    
    {% block container %}
    <div class="container">

      <div class="starter-template">
        <h1>New Project</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div><!-- /.container -->
    {% endblock container %}

    <!-- Site footer -->
    {% block footer %}
      <!-- Some social button for contact will do -->
      <a name="contact"></a>
      <div class="container">
            <div class="footer">
        <div class="row">
          <div class="col-lg-3">
              <p>&copy; TheTangoIndia {% now 'Y' %}</p>
          </div>
          <div class="col-lg-3 text-center">
            Connect with us on
            <a target="_blank" href="https://www.facebook.com/tangoinindia/"><i class="fa fa-facebook"></i> Facebook</a> or
            <a href="#"><i class="fa fa-twitter"></i> Twitter</a>
          </div>      
            <div class="fb-like" data-href="http://thetangoindia.in" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
          </div>
        </div>
      </div>
      <div class="container text-left">
         Disclaimer: We are totally a non-profit/non-business entity, with intention to provide info related to Argentine Tango in India at single place
     </div>
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

templates/copypaste.html
<head>
<style>
table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    text-align: left;
    padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}

th {
    background-color: #4CAF50;
    color: white;
}
</style>
</head>




<script
src="http://maps.googleapis.com/maps/api/js">
</script>

<script>
var myCenter=new google.maps.LatLng(17.4303968,78.4043325);

function initialize()
{
var mapProp = {
  center:myCenter,
  zoom:18
,
  mapTypeId:google.maps.MapTypeId.ROADMAP
  };

var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);

var marker=new google.maps.Marker({
  position:myCenter,
  });

marker.setMap(map);
}

google.maps.event.addDomListener(window, 'load', initialize);
</script>
</head>

<body>
<div id="googleMap" style="width:500px;height:380px;"></div>
</body>

templates/home.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Home{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="home" %}
{% endblock %}

{% block navbar-right %}
  {% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
<a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
  {% else %}
    {{ block.super }}
  {% endif %}
{% endblock %}

{% block splash %}
  <div class="jumbotron jumbotron-carousel corporate-jumbo">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-sm-8">
          <h1>{% include "_brandname.html" %}</h1>
          <p>Everything about Argentine Tango in India - Places, events, workshops, classes. This picture is from Holi Tango Festival - Auroville, India</p>
	  <a class="btn btn-primary" href="{% url 'Tango-Events' %}" role="button">See Events Posted By Tango Communities!</a>
        </div>
        <div class="col-md-4 col-sm-4">

        </div>
      </div>
    </div>
  </div>
{% endblock splash %}

{% block container %}
<!-- Benefits of the Django application -->

<div class="container">
  <div class="row">
    <div class="col-lg-4">
      <h2>Tango Hyderabad</h2>
      <p>Find Info about Tango in Hyderabad. </p>
      <p><a class="btn btn-primary" href="{% url 'Tango-In-Hyderabad' %}" role="button">Hyderabad Tango Club &raquo;</a></p>
    </div>
    <div class="col-lg-4">
      <h2>Tango Bangalore</h2>
      <p>Find Info about Tango in Bangalore. </p>
      <p><a class="btn btn-primary" href="{% url 'Tango-In-Bangalore' %}" role="button">Bangalore Argentine Tango &raquo;</a></p>
    </div>
    <div class="col-lg-4">
      <h2>Tango New Delhi</h2>
      <p>Find Info about Tango in New Delhi.</p>
      <p><a class="btn btn-primary" href="{% url 'Tango-In-Delhi' %}" role="button">NDTS - NewDelhi Tango School &raquo;</a></p>
    </div>
		<div class="col-lg-4">
      <h2>Tango Mumbai</h2>
      <p>Find Info about Tango in Mumbai</p>
      <p><a class="btn btn-primary" href="{% url 'Tango-In-Mumbai' %}" role="button">Tango Abrazo &raquo;</a></p>
    </div>
		<div class="col-lg-4">
      <h2>Tango Auroville</h2>
      <p>Find Info about Tango in Auroville-Pondicherry</p>
      <p><a class="btn btn-primary" href="{% url 'Tango-In-Auroville-Pondicherry' %}" role="button">Auroville Tango &raquo;</a></p>
    </div>
		<div class="col-lg-4">
      <h2>Tango Chennai</h2>
      <p>Find Info about Tango in Chennai</p>
      <p><a class="btn btn-primary" href="{% url 'Tango-In-Chennai' %}" role="button">View details &raquo;</a></p>
    </div>
		<div class="col-lg-4">
      <h2>Tango Pune</h2>
      <p>Find Info about Tango in Pune</p>
      <p><a class="btn btn-primary" href="{% url 'Tango-In-Pune' %}" role="button">Pune Tango Community &raquo;</a></p>
    </div>
		<div class="col-lg-4">
      <h2>Tango El Cabeceo</h2>
      <p>Find Info about Tango El Cabeceo - Bangalore </p>
      <p><a class="btn btn-primary" href="{% url 'Tango-In-Bangalore-El-Cabeceo' %}" role="button">El Cabeceo &raquo;</a></p>
    </div>
		 <div class="col-lg-4">
      <h2>BTangoConscious - Mumbai</h2>
      <p>Find Info about BTangoConscious - Mumbai </p>
      <p><a class="btn btn-primary" href="{% url 'Tango-In-Mumbai-BTangoConscious' %}" role="button">BTangoConscious &raquo;</a></p>
    </div>
		 <div class="col-lg-4">
      <h2>Goa Tango Community</h2>
      <p>Find Info about Goa Tango Community </p>
      <p><a class="btn btn-primary" href="{% url 'Tango-In-Goa' %}" role="button">Goa Tango Community &raquo;</a></p>
    </div>		
  </div>
</div>



{% endblock container %}

{% block scripts %}
<script src="{% static 'site/js/site.js' %}"></script>
{% endblock scripts %}